### ISSUE TITLE
render DAG diagram error

### ISSUE THREAD

**Issue by 4Denthusiast** [MovingBlocks/TeraMisc#55]
The diagram of the render graph at https://sketchboard.me/nAE1f4q2pDpd#/ , linked to from https://github.com/MovingBlocks/Terasology/wiki/Renderer , says that the chunksRefractiveReflectiveNode uses the defaultTextured shader program. It actually uses the chunk program.

**Comment by vampcat** [comment]
Thanks a ton for noticing - and reporting - this. It appears you are indeed correct. I'll wait for @emanuele3d to confirm this, and then we'll make the required changes.

Btw, I think this issue would have been better suited to the main Terasology repo :)

**Comment by Cervator** [comment]
I might be able to explain why it was submitted here: the engine wiki has a footer that suggests either fixing issues found or submitting an issue about it here to TeraMisc. Why? Because that footer edit dates from a whole other era, some 4 years ago, when TeraMisc was less active and there was a lot of noise in the engine repo/tracker. Nobody tell 4-year-ago-me about how we'd still hit 40+ PRs anyway ... ;-)

**Comment by emanuele3d** [comment]
Thanks for the report @4Denthusiast: I confirm the issue and it has now been fixed - might have been a cut&paste error at some point, with two or more nodes copied together and only one renamed.

@Cervator: can that link be fixed?

**Comment by Cervator** [comment]
@emanuele3d: done (see https://github.com/MovingBlocks/Terasology/wiki/_Footer/_edit). It is more of a process change than a fix, and likely a lot more related tweaks should be made, but no reason we can't update that one footer for now. I'll try to keep it in mind while updating the associated documentation system design stuff.

Closing as complete. Thanks all :-)
